name: Giphy API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Ruby 
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # Run RSpec tests
      - name: Run RSpec
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        run: bundle exec rspec
