nano .github/workflows/giphy-api-workflow.yml
name: Giphy API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Ruby (or your required runtime)
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7' # Replace with your Ruby version

      # Install dependencies (if you're using Bundler)
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Run tests
      - name: Run tests
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        run: |
          bundle exec rspec spec/giphy_search_spec.rb

